[project]
name = "pond"
version = "1.1.0"
description = "Semantic memory system for AI agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "httpx>=0.27.0",
    "asyncpg>=0.30.0",
    "pgvector>=0.3.0",
    "pydantic>=2.9.0",
    "pydantic-settings>=2.5.0",
    "numpy>=1.26.0",
    "click>=8.1.0",  # For CLI
    "spacy>=3.7.0",  # For NLP and entity extraction
    "inflect>=7.0.0",  # For tag normalization
    "pendulum>=3.0.0",  # For datetime parsing and formatting
    "pytimeparse>=1.1.8",  # For time parsing
    "aiohttp>=3.11.0",  # For Ollama HTTP client
    "structlog>=25.4.0",  # For structured logging
    "fastmcp>=1.0.0",  # For MCP server
    "jinja2>=3.1.0",  # For template rendering
    "alembic>=1.13.0",  # For database migrations
    "greenlet>=3.2.3",  # SQLAlchemy dependency
    "prometheus-client>=0.21.0",  # For metrics collection
    "prometheus-fastapi-instrumentator>=7.0.0",  # For automatic HTTP metrics
    "PyYAML>=6.0",  # For formatting health output in MCP server
    "en-core-web-lg",
]

[project.scripts]
pond = "pond.cli.main:cli"

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=5.0.0",
    "httpx>=0.27.0",  # For test client
]
dev = [
    "ruff>=0.8.0",  # Linting and formatting
    "pyright>=1.1.0",  # Type checking
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "auto"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "ollama: marks tests that require Ollama to be running (deselect with '-m \"not ollama\"')",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-asyncio>=1.1.0",
    "pytest-benchmark>=5.1.0",
]

[tool.uv]
package = true

[tool.uv.sources]
en-core-web-lg = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl" }

[tool.hatch.build.targets.wheel]
packages = ["src/pond"]

# Ruff configuration for linting and formatting
[tool.ruff]
line-length = 88
target-version = "py312"
src = ["src"]

[tool.ruff.lint]
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "I",     # isort (import sorting)
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "UP",    # pyupgrade
    "N",     # pep8-naming
    "ASYNC", # flake8-async
    "S",     # flake8-bandit (security)
    "DTZ",   # flake8-datetimez
    "RUF",   # ruff-specific rules
]
ignore = [
    "E501",   # Line too long (handled by formatter)
    "S101",   # Use of assert (needed for tests)
    "S104",   # Hardcoded bind all interfaces (0.0.0.0)
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S106"]  # Allow asserts and hardcoded passwords in tests

[tool.ruff.lint.isort]
known-first-party = ["pond"]

# Type checking with pyright
[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "All"
typeCheckingMode = "standard"
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
reportMissingTypeStubs = false
reportUnnecessaryTypeIgnoreComment = true
include = ["src"]
exclude = ["**/__pycache__", ".venv"]
